[package]
name = "tinyide"
version = "0.12.1"
description = "TinyIDE — быстрая IDE на Tauri 2, React и Monaco"
authors = ["tikhonneoplayneoplaydev"]
edition = "2021"
license = "AGPL-3.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1.11"
portable-pty = "0.9.0"
wasmi = "1.1.0"
base64 = "0.23.1"
rayon = "1.12.0"
reqwest = { version = "0.13", default-features = false, features = ["form", "json", "rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
argon2 = "0.5.3"
chacha20poly1305 = "0.11.0"
sha2 = "0.11.0"
rand_core = { version = "0.6", features = ["getrandom"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
