// ⚡ AUTO-GENERATED by scripts/gen-logos.mjs — не редактировать вручную
export const langLogos: Record<string, { color: string; svg: string }> = {
  "abap": {
    "color": "#e8274b",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e8274b\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">ABAP</text></svg>"
  },
  "apex": {
    "color": "#1797c0",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#1797c0\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Apex</text></svg>"
  },
  "azcli": {
    "color": "#0064ad",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#0064ad\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">AZ</text></svg>"
  },
  "bat": {
    "color": "#c1f12e",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#c1f12e\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">BAT</text></svg>"
  },
  "bicep": {
    "color": "#519aba",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#519aba\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Bicep</text></svg>"
  },
  "cameligo": {
    "color": "#3be133",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3be133\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">LIGO</text></svg>"
  },
  "clojure": {
    "color": "#db5855",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#db5855\"/>\n<path d=\"M24 18 q-6 6 -6 14 q0 8 6 14 M40 18 q6 6 6 14 q0 8 -6 14\" stroke=\"#fff\" stroke-width=\"4.5\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "coffee": {
    "color": "#244776",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#244776\"/>\n<path d=\"M16 26 h28 a8 8 0 0 1 0 16 h-28 a8 8 0 0 1 0 -16 z\" fill=\"none\" stroke=\"#fff\" stroke-width=\"3.6\"/>\n<path d=\"M44 30 h4 a5 5 0 0 1 0 10 h-4\" fill=\"none\" stroke=\"#fff\" stroke-width=\"3.6\"/>\n<path d=\"M18 48 h24\" stroke=\"#fff\" stroke-width=\"3.2\" stroke-linecap=\"round\"/>\n<path d=\"M24 18 q3 -4 0 -8 M34 18 q3 -4 0 -8\" stroke=\"#fff\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "cpp": {
    "color": "#f34b7d",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#00599c\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"25\" fill=\"#fff\">C++</text></svg>"
  },
  "csharp": {
    "color": "#512BD4",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#512bd4\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"25\" fill=\"#fff\">C#</text></svg>"
  },
  "csp": {
    "color": "#5c6bc0",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#5c6bc0\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">CSP</text></svg>"
  },
  "css": {
    "color": "#563d7c",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#264de4\"/><text x=\"32\" y=\"42\" text-anchor=\"middle\" font-family=\"ui-monospace,monospace\" font-weight=\"800\" font-size=\"30\" fill=\"#fff\">#</text></svg>"
  },
  "cypher": {
    "color": "#34c0eb",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#34c0eb\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Cypher</text></svg>"
  },
  "dart": {
    "color": "#00b4ab",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#00b4ab\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Dart</text></svg>"
  },
  "dockerfile": {
    "color": "#384d54",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#2496ed\"/>\n<rect x=\"16\" y=\"22\" width=\"33\" height=\"22\" rx=\"4\" fill=\"none\" stroke=\"#fff\" stroke-width=\"4\"/>\n<path d=\"M16 32 h33\" stroke=\"#fff\" stroke-width=\"4\"/>\n<path d=\"M9 28 q-4 0 -4 -3.5 M9 36 q-4 0 -4 -3.5\" stroke=\"#fff\" stroke-width=\"4\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "ecl": {
    "color": "#8a1267",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#8a1267\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">ECL</text></svg>"
  },
  "elixir": {
    "color": "#6e4a7e",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#6e4a7e\"/>\n<path d=\"M32 10 C 46 26 48 38 32 52 C 16 38 18 26 32 10 Z\" fill=\"#fff\"/>\n<path d=\"M24 38 q3 -4 6 0 q3 4 6 0\" stroke=\"#6e4a7e\" stroke-width=\"3\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "flow9": {
    "color": "#2d2d2d",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#2d2d2d\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">F9</text></svg>"
  },
  "freemarker2": {
    "color": "#8a6d3b",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#8a6d3b\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">FTL</text></svg>"
  },
  "fsharp": {
    "color": "#378bba",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#378bba\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">F#</text></svg>"
  },
  "go": {
    "color": "#00ADD8",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#00add8\"/>\n<text x=\"30\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"27\" fill=\"#fff\">Go</text>\n<path d=\"M44 46 q8 0 6 8\" stroke=\"#fff\" stroke-width=\"4\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "graphql": {
    "color": "#e10098",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e10098\"/>\n<path d=\"M32 12 L50 32 L32 52 L14 32 Z\" fill=\"none\" stroke=\"#fff\" stroke-width=\"4\" stroke-linejoin=\"round\"/>\n<path d=\"M32 19 L41 32 L32 45 L23 32 Z\" fill=\"#fff\" opacity=\"0.9\"/></svg>"
  },
  "handlebars": {
    "color": "#f7931e",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#f7931e\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">HB</text></svg>"
  },
  "hcl": {
    "color": "#844fba",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#844fba\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">HCL</text></svg>"
  },
  "html": {
    "color": "#e34c26",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e34c26\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"ui-monospace,monospace\" font-weight=\"800\" font-size=\"20\" fill=\"#fff\">&lt;/&gt;</text></svg>"
  },
  "ini": {
    "color": "#3f6faf",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3f6faf\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">INI</text></svg>"
  },
  "java": {
    "color": "#b07219",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#b07219\"/>\n<path d=\"M21 21 q4 -7 0 -13 M32 21 q4 -7 0 -13 M43 21 q4 -7 0 -13\" stroke=\"#fff\" stroke-width=\"3.2\" fill=\"none\" stroke-linecap=\"round\"/>\n<path d=\"M16 30 h26 a9 9 0 0 1 0 18 h-26 a9 9 0 0 1 0 -18 z\" fill=\"none\" stroke=\"#fff\" stroke-width=\"3.6\"/>\n<path d=\"M42 34 h5 a6 6 0 0 1 0 12 h-5\" fill=\"none\" stroke=\"#fff\" stroke-width=\"3.6\"/>\n<path d=\"M18 52 h22\" stroke=\"#fff\" stroke-width=\"3.2\" stroke-linecap=\"round\"/></svg>"
  },
  "javascript": {
    "color": "#f1e05a",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#f7df1e\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"24\" fill=\"#1a1a1a\">JS</text></svg>"
  },
  "julia": {
    "color": "#9558b2",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#9558b2\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Julia</text></svg>"
  },
  "kotlin": {
    "color": "#A97BFF",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#7f52ff\"/>\n<path d=\"M32 11 L53 32 L32 53 L11 32 Z\" fill=\"#fff\"/><text x=\"32\" y=\"40\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"24\" fill=\"#7f52ff\">K</text></svg>"
  },
  "less": {
    "color": "#1d365d",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#1d365d\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Less</text></svg>"
  },
  "lexon": {
    "color": "#1a5fab",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#1a5fab\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Lexon</text></svg>"
  },
  "liquid": {
    "color": "#67b8de",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#67b8de\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Liquid</text></svg>"
  },
  "lua": {
    "color": "#000080",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#000080\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Lua</text></svg>"
  },
  "m3": {
    "color": "#4e9a51",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#4e9a51\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">M3</text></svg>"
  },
  "markdown": {
    "color": "#083fa1",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#083fa1\"/>\n<text x=\"32\" y=\"36\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"25\" fill=\"#fff\">M</text>\n<path d=\"M32 42 v11 M26 47.5 l6 6 6-6\" stroke=\"#fff\" stroke-width=\"4\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"
  },
  "mdx": {
    "color": "#323232",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#323232\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">MDX</text></svg>"
  },
  "mips": {
    "color": "#d4a017",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#d4a017\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">MIPS</text></svg>"
  },
  "msdax": {
    "color": "#00758f",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#00758f\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">MSDAX</text></svg>"
  },
  "mysql": {
    "color": "#00758f",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#00758f\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">MySQL</text></svg>"
  },
  "objective-c": {
    "color": "#438eff",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#438eff\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">ObjC</text></svg>"
  },
  "pascal": {
    "color": "#e3f171",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e3f171\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#1a1a1a\">Pascal</text></svg>"
  },
  "pascaligo": {
    "color": "#3be133",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3be133\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">LIGO</text></svg>"
  },
  "perl": {
    "color": "#0298c3",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#0298c3\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Perl</text></svg>"
  },
  "pgsql": {
    "color": "#336791",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#336791\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">PgSQL</text></svg>"
  },
  "php": {
    "color": "#4F5D95",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#4F5D95\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">php</text></svg>"
  },
  "pla": {
    "color": "#6b7280",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#6b7280\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">PLA</text></svg>"
  },
  "postiats": {
    "color": "#1e4aec",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#1e4aec\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">ATS</text></svg>"
  },
  "powerquery": {
    "color": "#d24136",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#d24136\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">PQ</text></svg>"
  },
  "powershell": {
    "color": "#012456",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#012456\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">PS</text></svg>"
  },
  "protobuf": {
    "color": "#607d8b",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#607d8b\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Proto</text></svg>"
  },
  "pug": {
    "color": "#a86454",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#a86454\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Pug</text></svg>"
  },
  "python": {
    "color": "#3572A5",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3776ab\"/>\n<path d=\"M24 10 q16 -8 22 6 q6 14 -8 24 q-14 10 -16 24\" stroke=\"#ffd43b\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/>\n<path d=\"M40 10 q-16 -8 -22 6 q-6 14 8 24 q14 10 16 24\" stroke=\"#ffffff\" stroke-width=\"7\" fill=\"none\" stroke-linecap=\"round\"/>\n<circle cx=\"24\" cy=\"10\" r=\"5\" fill=\"#ffd43b\"/><circle cx=\"40\" cy=\"10\" r=\"5\" fill=\"#ffffff\"/>\n<circle cx=\"22.4\" cy=\"8.6\" r=\"1.4\" fill=\"#3776ab\"/><circle cx=\"38.4\" cy=\"8.6\" r=\"1.4\" fill=\"#3776ab\"/></svg>"
  },
  "qsharp": {
    "color": "#fed659",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#fed659\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#1a1a1a\">Q#</text></svg>"
  },
  "r": {
    "color": "#198ce7",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#198ce7\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">R</text></svg>"
  },
  "razor": {
    "color": "#512bd4",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#512bd4\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Razor</text></svg>"
  },
  "redis": {
    "color": "#d82c20",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#d82c20\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Redis</text></svg>"
  },
  "redshift": {
    "color": "#e4433d",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e4433d\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"12\" fill=\"#ffffff\">Redshift</text></svg>"
  },
  "restructuredtext": {
    "color": "#141414",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#141414\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">RST</text></svg>"
  },
  "ruby": {
    "color": "#701516",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#cc342d\"/>\n<path d=\"M32 8 L56 32 L32 56 L8 32 Z\" fill=\"none\" stroke=\"#fff\" stroke-width=\"4.5\" stroke-linejoin=\"round\"/>\n<path d=\"M32 20 L44 32 L32 44 L20 32 Z\" fill=\"#fff\" opacity=\"0.85\"/></svg>"
  },
  "rust": {
    "color": "#dea584",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#2a1f18\"/>\n<g stroke=\"#e05d2b\" stroke-width=\"4.5\" fill=\"none\" stroke-linecap=\"round\">\n<path d=\"M15 30 q-9 0 -5 10 M13 37 q-8 3 -3 11 M16 44 q-6 4 -1 11\"/>\n<path d=\"M49 30 q9 0 5 10 M51 37 q8 3 3 11 M48 44 q6 4 1 11\"/>\n</g>\n<circle cx=\"17\" cy=\"19\" r=\"8.5\" fill=\"#c9431c\"/><circle cx=\"13.5\" cy=\"15.5\" r=\"4.5\" fill=\"#2a1f18\"/>\n<circle cx=\"47\" cy=\"19\" r=\"8.5\" fill=\"#c9431c\"/><circle cx=\"50.5\" cy=\"15.5\" r=\"4.5\" fill=\"#2a1f18\"/>\n<ellipse cx=\"32\" cy=\"34\" rx=\"15\" ry=\"12\" fill=\"#e05d2b\"/>\n<circle cx=\"27\" cy=\"31\" r=\"2.4\" fill=\"#fff\"/><circle cx=\"37\" cy=\"31\" r=\"2.4\" fill=\"#fff\"/>\n<circle cx=\"27.6\" cy=\"31.7\" r=\"1.1\" fill=\"#2a1f18\"/><circle cx=\"37.6\" cy=\"31.7\" r=\"1.1\" fill=\"#2a1f18\"/>\n<path d=\"M27.5 39.5 q4.5 3.5 9 0\" stroke=\"#2a1f18\" stroke-width=\"2\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "sb": {
    "color": "#6b7280",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#6b7280\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">SB</text></svg>"
  },
  "scala": {
    "color": "#c22d40",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#c22d40\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Scala</text></svg>"
  },
  "scheme": {
    "color": "#1e4aec",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#1e4aec\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Scheme</text></svg>"
  },
  "scss": {
    "color": "#c6538c",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#c6538c\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">SCSS</text></svg>"
  },
  "shell": {
    "color": "#89e051",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3e5c2e\"/>\n<path d=\"M18 22 L30 32 L18 42\" stroke=\"#fff\" stroke-width=\"5\" fill=\"none\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n<path d=\"M34 44 h14\" stroke=\"#fff\" stroke-width=\"5\" stroke-linecap=\"round\"/></svg>"
  },
  "solidity": {
    "color": "#aa6746",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#aa6746\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">SOL</text></svg>"
  },
  "sophia": {
    "color": "#cc6687",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#cc6687\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Sophia</text></svg>"
  },
  "sparql": {
    "color": "#0c4597",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#0c4597\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">SPARQL</text></svg>"
  },
  "sql": {
    "color": "#e38c00",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e38c00\"/>\n<ellipse cx=\"32\" cy=\"19\" rx=\"15\" ry=\"5.5\" fill=\"#fff\"/>\n<path d=\"M17 19 v15 a15 5.5 0 0 0 30 0 V19\" fill=\"none\" stroke=\"#fff\" stroke-width=\"4\"/>\n<ellipse cx=\"32\" cy=\"28\" rx=\"15\" ry=\"5.5\" fill=\"none\" stroke=\"#fff\" stroke-width=\"2.6\" opacity=\"0.75\"/></svg>"
  },
  "st": {
    "color": "#58595b",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#58595b\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">ST</text></svg>"
  },
  "swift": {
    "color": "#F05138",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#f05138\"/>\n<path d=\"M12 46 Q 20 18 54 10 Q 38 22 28 34\" stroke=\"#fff\" stroke-width=\"5.5\" fill=\"none\" stroke-linecap=\"round\"/>\n<path d=\"M16 48 Q 26 40 34 46 Q 40 50 48 54\" stroke=\"#fff\" stroke-width=\"5.5\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "systemverilog": {
    "color": "#6a7cc9",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#6a7cc9\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">SV</text></svg>"
  },
  "tcl": {
    "color": "#e4cc98",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e4cc98\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">Tcl</text></svg>"
  },
  "twig": {
    "color": "#c1d026",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#c1d026\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">Twig</text></svg>"
  },
  "typescript": {
    "color": "#3178c6",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3178c6\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"24\" fill=\"#fff\">TS</text></svg>"
  },
  "typespec": {
    "color": "#2f6f37",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#2f6f37\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"12\" fill=\"#ffffff\">TypeSpec</text></svg>"
  },
  "vb": {
    "color": "#945db7",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#945db7\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">VB</text></svg>"
  },
  "wgsl": {
    "color": "#8f4fd1",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#8f4fd1\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">WGSL</text></svg>"
  },
  "xml": {
    "color": "#0060ac",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#0060ac\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">XML</text></svg>"
  },
  "yaml": {
    "color": "#cb171e",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#cb171e\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">YAML</text></svg>"
  },
  "json": {
    "color": "#3E7B27",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3e7b27\"/>\n<path d=\"M28 14 q-5 0 -5 5 v7 q0 4 -4 5 q4 1 4 5 v7 q0 5 5 5 M36 14 q5 0 5 5 v7 q0 4 4 5 q-4 1 -4 5 v7 q0 5 -5 5\" stroke=\"#fff\" stroke-width=\"4.5\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "jsonc": {
    "color": "#3E7B27",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3E7B27\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">JSONC</text></svg>"
  },
  "json5": {
    "color": "#3E7B27",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3E7B27\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">JSON5</text></svg>"
  },
  "vue": {
    "color": "#41b883",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#41b883\"/>\n<path d=\"M12 14 L32 52 L52 14 H41 L32 29 L23 14 Z\" fill=\"#fff\"/></svg>"
  },
  "svelte": {
    "color": "#ff3e00",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#ff3e00\"/>\n<path d=\"M42 18 C 46 20 48 25 46 30 C 44 35 38 37 32 39 C 27 41 23 43 23 48 C 23 52 26 55 30 56 L 28 51 C 26 50 26 47 28 45 C 30 42 35 40 40 38 C 45 36 50 33 50 26 C 50 20 46 16 40 15 Z\" fill=\"#fff\"/></svg>"
  },
  "toml": {
    "color": "#9c4221",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#9c4221\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">TOML</text></svg>"
  },
  "diff": {
    "color": "#d01919",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#d01919\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">±</text></svg>"
  },
  "tex": {
    "color": "#3d6117",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3d6117\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">LaTeX</text></svg>"
  },
  "latex": {
    "color": "#3d6117",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3d6117\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">LaTeX</text></svg>"
  },
  "asm": {
    "color": "#9c7a3c",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#9c7a3c\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">ASM</text></svg>"
  },
  "verilog": {
    "color": "#5c6bc0",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#5c6bc0\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"26\" fill=\"#ffffff\">V</text></svg>"
  },
  "vhdl": {
    "color": "#db4d3f",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#db4d3f\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">VHDL</text></svg>"
  },
  "makefile": {
    "color": "#427819",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#427819\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">Make</text></svg>"
  },
  "cmake": {
    "color": "#da3434",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#da3434\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">CMake</text></svg>"
  },
  "prisma": {
    "color": "#0c344b",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#0c344b\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"15\" fill=\"#ffffff\">Prisma</text></svg>"
  },
  "plaintext": {
    "color": "#9aa7c4",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#9aa7c4\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">TXT</text></svg>"
  },
  "batch": {
    "color": "#c1f12e",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#c1f12e\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#1a1a1a\">BAT</text></svg>"
  },
  "typescript2": {
    "color": "#3178c6",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3178c6\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"24\" fill=\"#fff\">TS</text></svg>"
  },
  "css2": {
    "color": "#563d7c",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#264de4\"/><text x=\"32\" y=\"42\" text-anchor=\"middle\" font-family=\"ui-monospace,monospace\" font-weight=\"800\" font-size=\"30\" fill=\"#fff\">#</text></svg>"
  },
  "scss2": {
    "color": "#c6538c",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#c6538c\"/><text x=\"32\" y=\"40.5\" text-anchor=\"middle\" font-family=\"system-ui,-apple-system,'Segoe UI',Roboto,sans-serif\" font-weight=\"800\" font-size=\"21\" fill=\"#ffffff\">SCSS</text></svg>"
  },
  "html2": {
    "color": "#e34c26",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#e34c26\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"ui-monospace,monospace\" font-weight=\"800\" font-size=\"20\" fill=\"#fff\">&lt;/&gt;</text></svg>"
  },
  "json2": {
    "color": "#3E7B27",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#3e7b27\"/>\n<path d=\"M28 14 q-5 0 -5 5 v7 q0 4 -4 5 q4 1 4 5 v7 q0 5 5 5 M36 14 q5 0 5 5 v7 q0 4 4 5 q-4 1 -4 5 v7 q0 5 -5 5\" stroke=\"#fff\" stroke-width=\"4.5\" fill=\"none\" stroke-linecap=\"round\"/></svg>"
  },
  "c++": {
    "color": "#f34b7d",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\"><rect width=\"64\" height=\"64\" rx=\"14\" fill=\"#00599c\"/><text x=\"32\" y=\"41\" text-anchor=\"middle\" font-family=\"system-ui,sans-serif\" font-weight=\"800\" font-size=\"25\" fill=\"#fff\">C++</text></svg>"
  }
};
